<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_data_apar extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
	
	function simpan
	(
		$no_apar,
		$jenis_apar,
		$kapasitas,
		$merek,
		$ket_apar
	)
	{
		$query = "
			INSERT INTO tb_apar
			(
				id_apar,
				no_apar,
				jenis_apar,
				kapasitas,
				merek,
				ket_apar,
				tgl_ins,
				user_ins
			)
			VALUES
			(
				(
					SELECT CONCAT(FRMTGL,ORD) AS id_apar
					From
					(
						SELECT CONCAT(Y,M,D) AS FRMTGL
						 ,CASE
							WHEN (ORD >= 10 AND ORD < 99) THEN CONCAT('000',CAST(ORD AS CHAR))
							WHEN (ORD >= 100 AND ORD < 999) THEN CONCAT('00',CAST(ORD AS CHAR))
							WHEN (ORD >= 1000 AND ORD < 9999) THEN CONCAT('0',CAST(ORD AS CHAR))
							WHEN ORD >= 10000 THEN CAST(ORD AS CHAR)
							ELSE CONCAT('0000',CAST(ORD AS CHAR))
							END As ORD
						From
						(
							SELECT
							CAST(LEFT(NOW(),4) AS CHAR) AS Y,
							CAST(MID(NOW(),6,2) AS CHAR) AS M,
							MID(NOW(),9,2) AS D,
							COALESCE(MAX(CAST(RIGHT(id_apar,5) AS UNSIGNED)) + 1,1) AS ORD
							From tb_apar
							WHERE DATE(tgl_ins) = DATE(NOW())
						) AS A
					) AS AA
				),
				
				'".$no_apar."',
				'".$jenis_apar."',
				'".$kapasitas."',
				'".$merek."',
				'".$ket_apar."',
				NOW(),
				'".$this->session->userdata('ses_gbl_nama_akun')."'
			)
		";
		
		/*SIMPAN DAN CATAT QUERY*/
			$this->db->query($query);
		/*SIMPAN DAN CATAT QUERY*/
	}
	
	function ubah
	(
		$id_apar,
		$no_apar,
		$jenis_apar,
		$kapasitas,
		$merek,
		$ket_apar
	)
	{
		$query = "
				UPDATE tb_apar SET
					no_apar = '".$no_apar."',
					jenis_apar = '".$jenis_apar."',
					kapasitas = '".$kapasitas."',
					merek = '".$merek."',
					ket_apar = '".$ket_apar."',
					tgl_updt = NOW(),
					user_updt = '".$this->session->userdata('ses_gbl_nama_akun')."'
				WHERE id_apar = '".$id_apar."'
				";
				
		/*SIMPAN DAN CATAT QUERY*/
			$this->db->query($query);
		/*SIMPAN DAN CATAT QUERY*/
	}
}

/* End of file M_data_apar.php */
/* Location: ./application/models/M_data_apar.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-30 15:11:17 */
/* http://harviacode.com */