<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_general extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
	
	function view_query_general($query)
	{
		$query = $this->db->query($query);
		if($query->num_rows() > 0)
		{
			return $query;
		}
		else
		{
			return false;
		}
	}
	
	function exec_query_general($query)
	{
		/*EKSEKUSI DULU QUERYNYA*/
			$this->db->query($query);
		/*EKSEKUSI DULU QUERYNYA*/
	}

	function get_akun($user,$pass)
	{
		$query = "SELECT * FROM tb_akun WHERE user = '".$user."' AND pass = '".$pass."';";
		$query = $this->db->query($query);
		if($query->num_rows() > 0)
		{
			return $query->row();
		}
		else
		{
			return false;
		}
	}
	
	function get_data_kantor()
	{
		$query = "SELECT * FROM tb_tentang";
		$query = $this->db->query($query);
		if($query->num_rows() > 0)
		{
			return $query->row();
		}
		else
		{
			return false;
		}
	}
}

/* End of file M_general.php */
/* Location: ./application/models/M_general.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-30 15:11:17 */
/* http://harviacode.com */